name: Jest CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: install
        run: yarn --check-files --frozen-lockfile --non-interactive

      - name: cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: checkout
        uses: actions/checkout@v2

      - name: restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: test
        run: yarn test:ci

      - name: coverage-master
        if: github.ref == 'refs/heads/master'
        run: npx netlify-cli deploy --dir=coverage --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          
      - name: coverage-pr
        id: coverage_pr
        if: github.event_name == 'pull_request'
        run: |
          npm install netlify-cli -g
          npx netlify-cli deploy --dir=coverage | tee result
          echo "::set-output name=result::$(cat result)"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: coverage-comment
        if: github.event_name == 'pull_request' && steps.coverage_pr.outputs.result != ''
        env:
          URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RESULT: ${{ steps.coverage_pr.outputs.result }}
        run: |
          BODY=$(echo $RESULT | grep "^Live Draft URL:" | sed "s/Live Draft URL:/Coverage report:/")
          echo "Commenting on PR:"
          echo $BODY
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "$BODY" }':  

    needs: setup
